### ISSUE TITLE
ArrayBuffer reference instead of string ...

### ISSUE THREAD

**Issue by DBoskic** [gauthier-th/apache-api#1]
File **parser.js** `function parseTag` line 58.. expects content to be string, but it gives ArrayBuffer, could you look at it, altering node_modules ... src not really solution for a long run using `content = String.fromCharCode.apply(null, new Uint16Array(content));` which had to be added to work. Could you issue an update with fix. 

Thank you very much for your good work.

**Comment by gauthier-th** [comment]
Hi, the error should be fixed.
Thanks for reporting me this out.
